export const content = {
 en: {
  nav:['Our work','Services','Our story'],quote:'Request a quote',call:'Call us',topline:'FAMILY CRAFTSMANSHIP. SOUTH FLORIDA LIVING.',
  eyebrow:'CUSTOM KITCHENS & CLOSETS · SOUTH FLORIDA',headline:['Beautiful spaces.','Thoughtfully built.'],
  intro:'Custom kitchens and closets made for the way you live. Family craftsmanship, personal attention, and over 30 years of experience—from the first idea to the final detail.',
  explore:'Explore our work',photoLabel:'A closer look at our craftsmanship',years:'YEARS OF CRAFT',note:'Designed for your life. Built to feel like home.',
  trust:['30+ years of experience','Family owned & operated','Design through installation'],
  projectsLabel:'SPACES WITH PURPOSE',projectsTitle:'Your home. More possibilities.',
  projectsIntro:'From a kitchen that brings everyone together to a closet that makes every morning easier. See what we can create for you.',
  kitchen:'Custom kitchens',closet:'Custom closets',viewGallery:'View gallery',
  kitchenDetail:'A place to gather. A space to create.',closetDetail:'A little more order. A lot more possibility.',
  servicesLabel:'MADE AROUND YOU',servicesTitle:'One team. Every detail.',
  services:[
   ['Kitchen remodeling','Bring new life to the heart of your home, with a layout and finishes that work for you.'],
   ['Custom closets','Make room for everything with thoughtful storage, tailored to your space and style.'],
   ['Cabinet refacing','Give your existing cabinetry a fresh look with carefully finished surfaces and details.'],
   ['Optional 3D design','See your ideas take shape before installation, with a clearer picture of the finished space.']
  ],
  storyLabel:'A FAMILY BEHIND EVERY FINISH',storyTitle:'Personal from the first conversation.',
  story:'We’re a family-owned kitchen and closet renovation company with more than 30 years of experience. We work closely with you to understand your home, guide your design choices, and bring the details together.',
  storySecond:'From your initial consultation to installation and finish work, you’ll have a team that cares about the result as much as you do.',
  reviewsLabel:'WORDS FROM OUR CUSTOMERS',reviewsTitle:'The details make the difference.',reviewsLink:'Read customer reviews',translation:'',
  reviews:[
   ['Rosa D.','Excellent job and customer service, great communication.'],
   ['Maria H.','The quality is outstanding, the level of professionalism is beyond expectations and they were worth every penny.'],
   ['Dalia B.','They worked on 2 of my kitchens and they did an amazing job!']
  ],
  areaLabel:'ROOTED IN SOUTH FLORIDA',areaTitle:'Crafted here. Made for your home.',
  areaIntro:'Serving homeowners across Broward and Miami-Dade. Tell us where your project is located and what you have in mind.',
  contactLabel:'LET’S TALK ABOUT YOUR SPACE',contactTitle:'Your next chapter starts at home.',
  contactIntro:'A new kitchen? A more organized closet? Tell us a little about your project. We’ll help you take the next step.',
  contactFallback:'Call or email us to discuss your project and request a quote.',
  email:'Email us',hours:'Monday–Friday · 9am–5pm',hoursNote:'Holiday hours may vary.',
  footer:'Custom spaces. Lasting craftsmanship.',back:'Back to home',
  galleryIntro:'A selection of real projects by Luciano Custom Kitchens & Closets. Explore the materials, storage, and details that make each space personal.',
  skip:'Skip to content',allRights:'All rights reserved.',privacy:'Privacy',close:'Close photo',openPhoto:'Enlarge photo',
  title:'Custom Kitchens & Closets in South Florida | Luciano',
  description:'Family-owned custom kitchens, closet remodeling, and cabinet refacing in Broward and Miami-Dade. Over 30 years of experience. Call Luciano to discuss your project.',
  galleryLabel:'OUR WORK, UP CLOSE',photo:'Project photo',survey:'Quote request form',surveyLink:'Open quote form',surveyHint:'If the form doesn’t appear, open it directly or call us.',
  privacyIntro:'We use the details you choose to share by phone, email, or quote form to respond to your project inquiry.',
  privacySurvey:'When enabled, quote forms are hosted by SurveyMonkey. Responses stay in our SurveyMonkey account and are not stored in this public website repository. Please avoid including sensitive personal information in your inquiry.',
  privacyAnalytics:'On our live business domain, Google Analytics measures page visits and contact-link interactions. We do not send your name, email, phone number, or project details to analytics. Opening a quote form is measured as an interaction, not a completed request.',
  privacyContact:'For questions about your inquiry or a request to access or delete information you shared, contact',
 },
 es: {
  nav:['Proyectos','Servicios','Nosotros'],quote:'Solicitar presupuesto',call:'Llámanos',topline:'TRADICIÓN FAMILIAR. HOGARES DEL SUR DE FLORIDA.',
  eyebrow:'COCINAS Y CLÓSETS A MEDIDA · SUR DE FLORIDA',headline:['Espacios únicos.','Hechos para ti.'],
  intro:'Cocinas y clósets a medida para tu forma de vivir. Un equipo familiar, atención personalizada y más de 30 años de experiencia, desde la primera idea hasta el último detalle.',
  explore:'Explora nuestros proyectos',photoLabel:'Los detalles de nuestro trabajo',years:'AÑOS DE OFICIO',note:'Diseñado para tu vida. Hecho para sentirte en casa.',
  trust:['Más de 30 años de experiencia','Una empresa familiar','Del diseño a la instalación'],
  projectsLabel:'ESPACIOS CON PROPÓSITO',projectsTitle:'Tu hogar. Más posibilidades.',
  projectsIntro:'Desde una cocina que reúne a todos hasta un clóset que facilita tus mañanas. Descubre lo que podemos crear para ti.',
  kitchen:'Cocinas a medida',closet:'Clósets a medida',viewGallery:'Ver galería',
  kitchenDetail:'Un lugar para reunirse. Un espacio para crear.',closetDetail:'Un poco más de orden. Muchas más posibilidades.',
  servicesLabel:'PENSADO PARA TI',servicesTitle:'Un equipo. Cada detalle.',
  services:[
   ['Remodelación de cocinas','Dale nueva vida al corazón de tu hogar con una distribución y acabados pensados para ti.'],
   ['Clósets a medida','Dale a cada cosa su lugar con soluciones de almacenamiento adaptadas a tu espacio y estilo.'],
   ['Renovación de gabinetes','Renueva la apariencia de tus gabinetes con superficies y detalles cuidadosamente terminados.'],
   ['Diseño 3D opcional','Visualiza tus ideas antes de la instalación y descubre cómo puede quedar tu espacio.']
  ],
  storyLabel:'UNA FAMILIA DETRÁS DE CADA DETALLE',storyTitle:'Cercanos desde la primera conversación.',
  story:'Somos una empresa familiar de renovación de cocinas y clósets con más de 30 años de experiencia. Trabajamos contigo para conocer tu hogar, orientarte en el diseño y cuidar cada detalle.',
  storySecond:'Desde la consulta inicial hasta la instalación y los acabados, contarás con un equipo al que le importa el resultado tanto como a ti.',
  reviewsLabel:'LO QUE DICEN NUESTROS CLIENTES',reviewsTitle:'Los detalles marcan la diferencia.',reviewsLink:'Lee las reseñas de clientes',translation:'Fragmentos traducidos del inglés.',
  reviews:[
   ['Rosa D.','Excelente trabajo y atención al cliente, muy buena comunicación.'],
   ['Maria H.','La calidad es excepcional, el profesionalismo supera las expectativas y valió cada centavo.'],
   ['Dalia B.','¡Trabajaron en dos de mis cocinas e hicieron un trabajo increíble!']
  ],
  areaLabel:'NUESTRAS RAÍCES, EN EL SUR DE FLORIDA',areaTitle:'Hecho aquí. Pensado para tu hogar.',
  areaIntro:'Atendemos a propietarios en Broward y Miami-Dade. Cuéntanos dónde está tu proyecto y qué tienes en mente.',
  contactLabel:'HABLEMOS DE TU ESPACIO',contactTitle:'Tu próxima etapa empieza en casa.',
  contactIntro:'¿Una cocina nueva? ¿Un clóset más organizado? Cuéntanos sobre tu proyecto. Te ayudaremos a dar el siguiente paso.',
  contactFallback:'Llámanos o escríbenos para hablar de tu proyecto y solicitar un presupuesto.',
  email:'Escríbenos',hours:'Lunes a viernes · 9 a. m.–5 p. m.',hoursNote:'El horario puede variar en días festivos.',
  footer:'Espacios a medida. Calidad que perdura.',back:'Volver al inicio',
  galleryIntro:'Una selección de proyectos reales de Luciano Custom Kitchens & Closets. Explora los materiales, el almacenamiento y los detalles que hacen único cada espacio.',
  skip:'Saltar al contenido',allRights:'Todos los derechos reservados.',privacy:'Privacidad',close:'Cerrar foto',openPhoto:'Ampliar foto',
  title:'Cocinas y clósets a medida en el sur de Florida | Luciano',
  description:'Empresa familiar de cocinas a medida, remodelación de clósets y renovación de gabinetes en Broward y Miami-Dade. Más de 30 años de experiencia.',
  galleryLabel:'NUESTROS PROYECTOS, DE CERCA',photo:'Foto del proyecto',survey:'Formulario de presupuesto',surveyLink:'Abrir formulario',surveyHint:'Si no aparece el formulario, ábrelo directamente o llámanos.',
  privacyIntro:'Usamos la información que compartes por teléfono, correo o formulario para responder a tu consulta sobre un proyecto.',
  privacySurvey:'Cuando están habilitados, SurveyMonkey aloja los formularios de presupuesto. Las respuestas permanecen en nuestra cuenta de SurveyMonkey y no se guardan en el repositorio público de este sitio. Evita incluir información personal sensible.',
  privacyAnalytics:'En nuestro dominio comercial, Google Analytics mide visitas e interacciones con los enlaces de contacto. No enviamos tu nombre, correo, teléfono ni detalles del proyecto a Analytics. Abrir el formulario cuenta como una interacción, no como una solicitud completada.',
  privacyContact:'Para preguntas sobre tu consulta o para solicitar acceso o eliminación de la información compartida, escribe a',
 }
} as const;
